POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: 

{
    "title": "final test one",
    "author": "you!",
    "url": "https://URLS.com",
    "likes": 4
}

###

GET http://localhost:3001/api/blogs
Content-Type: application/json

{
}

###
GET http://localhost:3001/api/blogs/67be4ee17c2afdfef42fffaf
Content-Type: application/json

{
}

###

POST http://localhost:3001/api/blogs/67be4ee17c2afdfef42fffaf/comments
Content-Type: application/json
Authorization: 


{
    "content": "this is a comment"
}

###
DELETE http://localhost:3001/api/blogs/67be3cb829756768659698ae
Content-Type: application/json
Authorization: