POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: 

{
    "title": "final test one",
    "author": "you!",
    "url": "https://URLS.com",
    "likes": "4"
}

###

GET http://localhost:3001/api/blogs
Content-Type: application/json

{
}

###

DELETE http://localhost:3001/api/blogs/67a6570f5033180ca934ee55
Content-Type: application/json
Authorization: